development:
  adapter: postgresql
  encoding: unicode
  database: dabbleform_development
  pool: 5
  username: rsj
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: dabbleform_test
  pool: 5
  username: rsj
  password: 
