# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 776ad2c6400c3d5d48f42ae7a317674a09d9e05d7fb70579b66b89fb617ca424832a96a4bd7750e3c8a9782620936528c2d50c57b7d10fbc11818e5ef53bb284

test:
  secret_key_base: a1fff2fce7370b82326a28ac07db247d8c661945ce95f92f0f18f773c804fc619cde66867676788ee6b79f86374af09032fa68f9b4e543cd313bbd9fc6e49946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
